name: dart_bloc_mbt_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
#   path: ^1.8.0
  bloc: ^8.0.3
  equatable: ^2.0.3
  mason: ^0.1.0-dev.31
  state_machine: 
    git: https://github.com/IvoSchols/state_machine.git

dev_dependencies:
  bloc_test: ^9.0.3
  lints: ^2.0.0
  test: ^1.16.0
