name: dart_bloc_mbt_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
#   path: ^1.8.0
  analyzer: ^4.3.1
  binary_expression_tree:
    git: https://github.com/IvoSchols/dart-binary-expression-tree
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  equatable: ^2.0.3
  mason: ^0.1.0-dev.31
  path: ^1.8.2
  pub_semver: ^2.1.1
  state_machine: 
    git: https://github.com/IvoSchols/state_machine.git
  test: ^1.21.4

dev_dependencies:
  lints: ^2.0.0
