name: dart_bloc_mbt_generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
#   path: ^1.8.0
  analyzer: ^4.3.1
  binary_expression_tree:
    git: https://github.com/IvoSchols/dart-binary-expression-tree
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  collection: ^1.16.0
  dart_z3:
    git: https://github.com/IvoSchols/dart-z3
  equatable: ^2.0.3
  path: ^1.8.2
  pub_semver: ^2.1.1
  state_machine: 
    git: https://github.com/IvoSchols/dart-state-machine
  test: ^1.21.4
  tree_iterator: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
